In [1]:
import torch
import numpy as np

### Creating and Operating Torch Tensors

In [2]:
x = torch.empty(2,2)
x

tensor([[-1.4111e-37,  1.2822e-42],
        [ 0.0000e+00,  0.0000e+00]])

In [4]:
x = torch.rand(2,3)
x

tensor([[0.1187, 0.5888, 0.8795],
        [0.4706, 0.8706, 0.0607]])

In [5]:
x = torch.ones(4,2) #similar for zeros
x

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [6]:
print(x.dtype)

torch.float32


In [8]:
x = torch.eye(3, dtype=torch.int)
x

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]], dtype=torch.int32)

In [9]:
x = torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [11]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x+y
print(z)

tensor([[0.0036, 0.7788],
        [0.5464, 0.3238]])
tensor([[0.2049, 0.3071],
        [0.6437, 0.5633]])
tensor([[0.2086, 1.0859],
        [1.1900, 0.8872]])


In [12]:
torch.add(x,y) #torch.sub(x, y) -> element wise subtraction

tensor([[0.2086, 1.0859],
        [1.1900, 0.8872]])

In [13]:
torch.mul(x, y) #element wise matrix multiplication.

tensor([[0.0007, 0.2392],
        [0.3517, 0.1824]])

In [14]:
x*y #element wise multiplication

tensor([[0.0007, 0.2392],
        [0.3517, 0.1824]])

In [14]:
x = torch.rand(2,3)
print(x)

tensor([[0.5444, 0.4572, 0.1721],
        [0.8924, 0.5640, 0.8482]])


In [15]:
# Transpose entire matrix
x.T

tensor([[0.5444, 0.8924],
        [0.4572, 0.5640],
        [0.1721, 0.8482]])

**.transpose** 
- .transpose(input, dim0, dim1): it swaps dim0 and dim1

In [20]:
# .transpose(input, dim0, dim1)


In [23]:
x = torch.rand(3,2,2)
x.size() # created a 3D tensor, or a list of 3 tensor

torch.Size([3, 2, 2])

In [34]:
x[0][:][:] # 0th dimension represent entire tensor

tensor([[0.0567, 0.2712],
        [0.5408, 0.6115]])

In [36]:
x[0][0][:] # 1st dimension represent entire row

tensor([0.0567, 0.2712])

In [ ]:
# and the 2nd dimension represent the column

In [30]:
print(x)

tensor([[[0.0567, 0.2712],
         [0.5408, 0.6115]],

        [[0.8543, 0.0889],
         [0.1819, 0.0730]],

        [[0.7066, 0.5724],
         [0.3822, 0.2085]]])


In [44]:
# Now we want to transpose each individual tensor, hence we want to replace 1st(row) and 2nd(cols) dimension.
# we won't chang 0th dimension it is individual tensor's position.
torch.transpose(x, 1, 2)

tensor([[[0.0567, 0.5408],
         [0.2712, 0.6115]],

        [[0.8543, 0.1819],
         [0.0889, 0.0730]],

        [[0.7066, 0.3822],
         [0.5724, 0.2085]]])

*Now we have transposed each matrix individually.*

### Slicing

In [15]:
x = torch.rand(5,3)
print(x)
print(x[:,0]) # All the rows, but only 0th column

tensor([[0.0570, 0.6281, 0.0916],
        [0.6184, 0.9647, 0.1983],
        [0.3455, 0.0257, 0.2636],
        [0.5358, 0.1768, 0.4938],
        [0.2383, 0.1518, 0.3122]])
tensor([0.0570, 0.6184, 0.3455, 0.5358, 0.2383])


In [16]:
print(x[1,:]) # All the columns of 2nd row

tensor([0.6184, 0.9647, 0.1983])


In [18]:
x[1,1]

tensor(0.9647)

In [19]:
x[1,1].item()

0.9646966457366943

### Reshape and Inter-Conversion

In [30]:
x = torch.eye(4)
y = x.view(16)

In [31]:
y

tensor([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

In [32]:
y = x.view(8,2)
y

tensor([[1., 0.],
        [0., 0.],
        [0., 1.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 1.]])

In [35]:
y = x.view(-1,2,4)
y

tensor([[[1., 0., 0., 0.],
         [0., 1., 0., 0.]],

        [[0., 0., 1., 0.],
         [0., 0., 0., 1.]]])

In [36]:
y.size()

torch.Size([2, 2, 4])

In [38]:
# Convert torch tensor into numpy
a = torch.ones(5)
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [39]:
# Convert numpy into torch tensor
a = np.ones(5)
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [40]:
b += 1
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [41]:
a

array([2., 2., 2., 2., 2.])

**Note**: a and b will point to same location if only CPU is used. Be careful while modifying any of them.

In [42]:
x = torch.ones(5, requires_grad = True)

**Note**: requires_grad is by default False. If it is True, then it tells the pytorch that 'x' will be optimized in further steps, hence we will need its gradient.

### Matrix Multiplication

In [5]:
x = torch.eye(3)
y = torch.rand(3,1)
print(x)
print(y)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[0.3786],
        [0.8927],
        [0.0741]])


In [6]:
# (3,3) X (3,1) => (3,1)
z = torch.matmul(x,y)

In [7]:
z

tensor([[0.3786],
        [0.8927],
        [0.0741]])

**torch.bmm(ip1, ip2)**
- performs batch matrix-matrix product
- input : 2 3d-tensors containing same number of matrices dim(ip1) => (b, n, m), dim(ip2) => (b, m, p)
- output : dim(bmm()) => (b,n,p)

In [9]:
mat1 = torch.randn(10, 3, 4)
mat2 = torch.randn(10, 4, 5)

In [10]:
res = torch.bmm(mat1, mat2)

In [11]:
res.size()

torch.Size([10, 3, 5])